### ISSUE TITLE
Page layouts

### ISSUE THREAD

**Issue by rishson** [dojo/examples#15]
`Non-functional requirement`

- [ ] The home page should be the first page displayed after the user has logged in.
- [ ] The home page should consist of a header, main section and footer.
- [ ] The header should not scroll out of view when the page is scrolled, but the main section and footer should scroll if they extend below the fold.
- [ ] If the height of the main section is less than the viewport height, then the footer should align to the bottom of the page (sticky footer).

**Comment by rishson** [comment]
@itorrey the requirements are just off the top of my head, please feel free to amend them 😄

**Comment by rishson** [comment]
[Home page layout](https://drive.google.com/a/sitepen.com/file/d/0B_iJTK6sYbwKTV9tUDZRZmFLY0U/view?pli=1)

**Comment by agubler** [comment]
Completed.
